language: java
install: true
os: linux
dist: bionic
jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
addons:
  sonarcloud:
    organization: bajek
    token:
      secure: "vtXph6aoVuwGaRRmgDAak9I3T3lmRKM2r89DzrkZrOYSyWk9N+ec21LSZRWK4CIQ+BMFVbrYHfDFVVLXUQg4xHetgwR9ASFQ98B7fUpsY59nvo+hb3P2Y4uHTGrrWUzqXiXd98C9Gk3gOklHDNFUSta/XNHtWepzKLnSPZDzurfZWYretm76udgLyyD/CWZdYlmoVecs5TXZqQa6RVusk+CxiYoAGypktBsPi3AfjUq2iAOP+b8p2dS+8JdYms9d2fjsi6PU9dyBORVfjvFCoykq441UBevh3zAOZ0J2fhqvH1/qZZCBMgL3eGzYascFm8VKTOAFtFeAMJtJMb/PnN0HWIvbOSeE91Gg129UJqYt8U+dYsLRmq4+wZxVnxXyeWIAUrJW7yNQgRNzs9yAgWz8ndFWNdG9W9TjYJY42fH9cYSAyMWTQBa87P1GWIFiOMDKajT9mIg3KwGxUvQM07eTnpHkGO8WbAMbqqy+jXseeTTv//0Gf+g1TtLDOm0ICRbpN1RDcYxl08R01cEb4zMWcOMhPxCBl7ieaSxlrXL0+e5i+D3unWhcSjQ8qiuRNEeW69dwJ2xua5dhawdulXOXAN4OIiLPOA+yLq8iJ5UGIb8F3yUWpTbqVjDIFptBGNc3/IZctdz01HhAvYDaAbhC19yRPcIDD3cOEq6uf4k="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Bajek_u-vod-getter
